apiVersion: v1
kind: Pod
metadata: 
 name: postgres-pod
 labels: 
  app: voting-app
  type: postgres
spec: 
 containers: 
  - name: postgres-container
    image: postgres:9.4
    ports: 
     - containerPort: 5432
