apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: demo-voating-app
    name: postgres-pod
spec:
  containers:
    - name: postgres-pod
      image: postgres:9.4
      ports:
        - containerPort: 5432
