apiVersion: v1
kind: Pod
metadata: 
 name: postgres-pod
 labels:  
  name: postgers-pod
  app: voting-app
spec: 
 containers: 
  - name: postgres-container
    image: postgres
    ports: 
     - containerPort: 5432
