apiVersion: v1
kind: Pod
metadata: 
 name: result-app
 labels: 
  name: result-app
  app: voting-app
spec: 
 containers: 
  - name: result-app
    image: dockersamples/examplevotingapp_worker
    ports: 
     - containerPort: 8080
