apiVersion: v1
kind: Service
metadata:
  name: result-app
  labels:
    name: result-app
    app: demo-voating-app
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    name: result-app-pod
    app: demo-voating-app