apiVersion: v1
kind: Service
metadata:
  name: voating-app
  labels:
    name: voating-app-service
    app: demo-voating-app
spec:
  type: LoadBanlancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    name: voating-app-service
    app: demo-voating-app
