apiVersion: v1
kind: Pod
metadata: 
 name: voting-app-pod
 labels: 
  name: voting-app-pod
  app: voting-app
spec: 
 containers: 
  - name: voating-app
    image: dockersamples/examplevotingapp_vote
    ports: 
     - containerPort: 8080

