apiVersion: apps/v1
kind: Deployment
metadata: 
 name: worker-app-dep
 labels: 
   name: worker-app-pod
   app: voting-app 
spec: 
 replicas: 3 
 selector: 
  matchLabels: 
   name: worker-app-pod
   app: voting-app
 template: 
  metadata: 
   name: worker-app-pod
   app: voting-app
  spec: 
   containers: 
    - name: worker-app-pod
      image: docker/example-voting-app-worker 
